#ifndef SHADER_UNIFORMS_H
#define SHADER_UNIFORMS_H

namespace ShaderUniforms{
	enum{MVP,MODEL,STEP_SIZE,VIEW_DIRECTION,CAMERA_POSITION
		,LIGHT_COLOR
		,LIGHT_DIRECTION,LIGHT_DIRECTIONAL,NUM_DIRECTIONAL_LIGHTS,LIGHT_POINT,NUM_POINT_LIGHTS
		,MATERIAL_DIFFUSE,MATERIAL_AMBIENT,MATERIAL_SPECULAR,MATERIAL_SHININESS
		,NUM_UNIFORMS};

	
}

#endif